services:
  - type: web
    name: umm-reham-api
    runtime: docker
    dockerfilePath: Dockerfile
    plan: free
    region: frankfurt
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:10000;http://+:8080
      - key: Jwt__Key
        value: UmmReham_SuperSecret_Key_2024_SaudiArabia_Academic_Platform_!@#
      - key: Jwt__Issuer
        value: UmmReham
      - key: Jwt__Audience
        value: UmmRehamAdmin
